#!/usr/bin/env bash
# Bash script that uses ssh to connet to your server using the private
# key ~/.ssh/school with the user ubuntu
# ssh ubuntu@100.25.26.221 -i ~/.ssh/school
ssh -i ~/.ssh/school ubuntu@100.25.26.221
